pipeline {
    agent { label 'linux' }

    stages {
        stage('Hello') {
            steps {
                echo ${test_message} 
                publishEvent simpleEvent('helloWorld')
            }
        }
    }
}

