pipeline {
    agent {
      kubernetes {
        label "centos-7-pod-template"
      }
    }

    stages {
        stage('Hello') {
            steps {
                echo "${test_message}"
                //publishEvent simpleEvent('helloWorld')
            }
        }
    }
}

