pipeline {
  agent {
    kubernetes {
      defaultContainer 'centos7'
      yamlFile 'podTemplates/centos7.yaml'
    }
  }
    stages {
        stage('Hello') {
            steps {
                echo "${test_message}"
                //publishEvent simpleEvent('helloWorld')
            }
        }
    }
}

